// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "./internal/discovery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lights$0 from "./internal/lights/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "./internal/screensync/capture/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ActivateScene(id: string): $CancellablePromise<void> {
    return $Call.ByID(2498763824, id);
}

/**
 * AddElgatoByIP adds an Elgato Key Light by IP when auto-discovery fails
 * (e.g. mDNS is blocked on Windows). Use the device's LAN IP (e.g. 192.168.4.73).
 */
export function AddElgatoByIP(ip: string): $CancellablePromise<lights$0.Device> {
    return $Call.ByID(2259389224, ip).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AddHueBridge(ip: string, username: string): $CancellablePromise<void> {
    return $Call.ByID(2527221499, ip, username);
}

export function CheckCameraNow(): $CancellablePromise<boolean> {
    return $Call.ByID(219071560);
}

export function CloneScene(id: string): $CancellablePromise<store$0.Scene> {
    return $Call.ByID(2800479482, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateScene(req: $models.CreateSceneRequest): $CancellablePromise<store$0.Scene> {
    return $Call.ByID(2007345907, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeactivateScene(): $CancellablePromise<void> {
    return $Call.ByID(2036730921);
}

export function DeleteScene(id: string): $CancellablePromise<void> {
    return $Call.ByID(3853166994, id);
}

export function DiscoverHueBridges(): $CancellablePromise<discovery$0.DiscoveredHueBridge[]> {
    return $Call.ByID(236926698).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DiscoverLights(): $CancellablePromise<$models.DiscoverResult> {
    return $Call.ByID(2131782059).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetActiveScene(): $CancellablePromise<string> {
    return $Call.ByID(1760025247);
}

export function GetCameraState(): $CancellablePromise<boolean> {
    return $Call.ByID(1987907445);
}

export function GetCapturePreview(): $CancellablePromise<string> {
    return $Call.ByID(3614085649);
}

export function GetDefaultScreenSyncConfig(): $CancellablePromise<store$0.ScreenSyncConfig> {
    return $Call.ByID(789626461).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetDevices(): $CancellablePromise<lights$0.Device[]> {
    return $Call.ByID(2647233474).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetHueBridges(): $CancellablePromise<store$0.HueBridge[]> {
    return $Call.ByID(2584770935).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetLastSceneID(): $CancellablePromise<string> {
    return $Call.ByID(3308438680);
}

export function GetLightState(deviceID: string): $CancellablePromise<lights$0.DeviceState> {
    return $Call.ByID(124515690, deviceID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetMonitors(): $CancellablePromise<capture$0.MonitorInfo[]> {
    return $Call.ByID(3692271108).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetScene(id: string): $CancellablePromise<store$0.Scene> {
    return $Call.ByID(3126298765, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetScenes(): $CancellablePromise<store$0.Scene[]> {
    return $Call.ByID(1439475674).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetScreenSyncState(): $CancellablePromise<$models.ScreenSyncState> {
    return $Call.ByID(2507334345).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetSettings(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetWindowThumbnail(hwnd: number): $CancellablePromise<string> {
    return $Call.ByID(309206597, hwnd);
}

export function GetWindows(): $CancellablePromise<capture$0.WindowInfo[]> {
    return $Call.ByID(698877140).then(($result: any) => {
        return $$createType16($result);
    });
}

export function IsMonitoringEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(372943236);
}

/**
 * OpenConfigFile opens the config.json file in the system's default application.
 */
export function OpenConfigFile(): $CancellablePromise<void> {
    return $Call.ByID(2165811885);
}

/**
 * OpenLightsPopup shows the lights popup window. Created on first call;
 * recreated after being closed (Wails 3 destroys the window on close).
 */
export function OpenLightsPopup(): $CancellablePromise<void> {
    return $Call.ByID(1945892682);
}

export function PairHueBridge(ip: string): $CancellablePromise<$models.PairResult> {
    return $Call.ByID(2425822496, ip).then(($result: any) => {
        return $$createType17($result);
    });
}

export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(3730234565);
}

export function RemoveDevice(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(2755636563, deviceID);
}

export function RemoveHueBridge(id: string): $CancellablePromise<void> {
    return $Call.ByID(1846300572, id);
}

export function SetDeviceRoom(deviceID: string, room: string): $CancellablePromise<void> {
    return $Call.ByID(3623922862, deviceID, room);
}

export function SetLightState(deviceID: string, state: lights$0.DeviceState): $CancellablePromise<void> {
    return $Call.ByID(1544172278, deviceID, state);
}

export function SetMonitoringEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(880108070, enabled);
}

export function StartRegionSelect(): $CancellablePromise<void> {
    return $Call.ByID(3020050511);
}

export function StopScreenSync(): $CancellablePromise<void> {
    return $Call.ByID(3174675542);
}

export function TurnOffLight(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(360115145, deviceID);
}

export function TurnOnLight(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(1365421781, deviceID);
}

export function UpdateScene(scene: store$0.Scene): $CancellablePromise<void> {
    return $Call.ByID(2649004148, scene);
}

export function UpdateScreenSyncConfig(sceneID: string, cfg: store$0.ScreenSyncConfig): $CancellablePromise<void> {
    return $Call.ByID(2981736081, sceneID, cfg);
}

export function UpdateSettings(settings: store$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(2894041249, settings);
}

// Private type creation functions
const $$createType0 = lights$0.Device.createFrom;
const $$createType1 = store$0.Scene.createFrom;
const $$createType2 = discovery$0.DiscoveredHueBridge.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.DiscoverResult.createFrom;
const $$createType5 = store$0.ScreenSyncConfig.createFrom;
const $$createType6 = $Create.Array($$createType0);
const $$createType7 = store$0.HueBridge.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = lights$0.DeviceState.createFrom;
const $$createType10 = capture$0.MonitorInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($$createType1);
const $$createType13 = $models.ScreenSyncState.createFrom;
const $$createType14 = store$0.Settings.createFrom;
const $$createType15 = capture$0.WindowInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.PairResult.createFrom;
