// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lights$0 from "./internal/lights/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export class CreateSceneRequest {
    "name": string;
    "trigger": string;
    "devices": { [_ in string]?: lights$0.DeviceState };
    "globalColor"?: lights$0.Color | null;
    "globalKelvin"?: number | null;
    "screenSync"?: store$0.ScreenSyncConfig | null;

    /** Creates a new CreateSceneRequest instance. */
    constructor($$source: Partial<CreateSceneRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("trigger" in $$source)) {
            this["trigger"] = "";
        }
        if (!("devices" in $$source)) {
            this["devices"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSceneRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSceneRequest {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField2_0($$parsedSource["devices"]);
        }
        if ("globalColor" in $$parsedSource) {
            $$parsedSource["globalColor"] = $$createField3_0($$parsedSource["globalColor"]);
        }
        if ("screenSync" in $$parsedSource) {
            $$parsedSource["screenSync"] = $$createField5_0($$parsedSource["screenSync"]);
        }
        return new CreateSceneRequest($$parsedSource as Partial<CreateSceneRequest>);
    }
}

export class DiscoverResult {
    "devices": lights$0.Device[];
    "errors"?: string[];

    /** Creates a new DiscoverResult instance. */
    constructor($$source: Partial<DiscoverResult> = {}) {
        if (!("devices" in $$source)) {
            this["devices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoverResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoverResult {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField0_0($$parsedSource["devices"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField1_0($$parsedSource["errors"]);
        }
        return new DiscoverResult($$parsedSource as Partial<DiscoverResult>);
    }
}

export class PairResult {
    "success": boolean;
    "username": string;
    "error"?: string;

    /** Creates a new PairResult instance. */
    constructor($$source: Partial<PairResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PairResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PairResult($$parsedSource as Partial<PairResult>);
    }
}

export class ScreenSyncState {
    "running": boolean;
    "sceneId": string;

    /** Creates a new ScreenSyncState instance. */
    constructor($$source: Partial<ScreenSyncState> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("sceneId" in $$source)) {
            this["sceneId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenSyncState instance from a string or object.
     */
    static createFrom($$source: any = {}): ScreenSyncState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenSyncState($$parsedSource as Partial<ScreenSyncState>);
    }
}

// Private type creation functions
const $$createType0 = lights$0.DeviceState.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = lights$0.Color.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = store$0.ScreenSyncConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = lights$0.Device.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
