// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lights$0 from "../lights/models.js";

/**
 * AssignmentStrategy selects how extracted colors are mapped to devices.
 */
export enum AssignmentStrategy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * AssignmentStrategyIdentityLock anchors each device to a stable color and
     * only allows reassignment when the color has shifted significantly.
     */
    AssignmentStrategyIdentityLock = "identity_lock",

    /**
     * AssignmentStrategyFlowTrack matches colors to per-device EMA trajectories.
     * Adapts smoothly to gradual content changes without sudden swaps.
     */
    AssignmentStrategyFlowTrack = "flow_track",

    /**
     * AssignmentStrategySceneCutRemap uses trajectory matching during steady
     * state and performs a fresh global remap on detected scene cuts.
     */
    AssignmentStrategySceneCutRemap = "scene_cut_remap",

    /**
     * AssignmentStrategyZoneDominant maps color[i] to device[i] permanently.
     * Maximum stability — never reassigns devices.
     */
    AssignmentStrategyZoneDominant = "zone_dominant",
};

/**
 * BrightnessMode clamps the output brightness to a range.
 */
export enum BrightnessMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BrightnessModeDynamic = "fully_dynamic",
    BrightnessModeDark = "dark",
    BrightnessModeMedium = "medium",
    BrightnessModeBright = "bright",
    BrightnessModeFullBright = "full_bright",
};

/**
 * CaptureMode defines how the screen is captured.
 */
export enum CaptureMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CaptureModeMonitor = "monitor",
    CaptureModeRegion = "region",
    CaptureModeWindow = "window",
    CaptureModeActiveWindow = "active_window",
};

/**
 * CaptureRect defines a rectangular screen region.
 */
export class CaptureRect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new CaptureRect instance. */
    constructor($$source: Partial<CaptureRect> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureRect instance from a string or object.
     */
    static createFrom($$source: any = {}): CaptureRect {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaptureRect($$parsedSource as Partial<CaptureRect>);
    }
}

/**
 * ColorMode controls whether to extract one or multiple colors.
 */
export enum ColorMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ColorModeSingle = "single",
    ColorModeMulti = "multi",
};

/**
 * ExtractionMethod selects which algorithm picks the representative color.
 */
export enum ExtractionMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ExtractionMethodDominant = "dominant",
    ExtractionMethodBrightest = "brightest",
    ExtractionMethodSaturated = "saturated",
    ExtractionMethodDiverse = "diverse",

    /**
     * ExtractionMethodVivid weights each pixel's vote by saturation² so colorful
     * regions dominate over dull backgrounds without losing area awareness.
     * Best sub-method for spatial_grid when the subject is more saturated than
     * its background (flowers, games, movies).
     */
    ExtractionMethodVivid = "vivid",
};

export class HueBridge {
    "id": string;
    "ip": string;
    "username": string;

    /** Creates a new HueBridge instance. */
    constructor($$source: Partial<HueBridge> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HueBridge instance from a string or object.
     */
    static createFrom($$source: any = {}): HueBridge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HueBridge($$parsedSource as Partial<HueBridge>);
    }
}

/**
 * MultiColorApproach selects the multi-color strategy.
 */
export enum MultiColorApproach {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MultiColorSpatialGrid = "spatial_grid",
    MultiColorScenePalette = "scene_palette",
};

export class Scene {
    "id": string;
    "name": string;
    "trigger": string;
    "devices": { [_ in string]?: lights$0.DeviceState };

    /**
     * GlobalColor/GlobalKelvin persist the editor's global override so it can
     * be restored when the scene is re-opened for editing.
     */
    "globalColor"?: lights$0.Color | null;
    "globalKelvin"?: number | null;

    /**
     * ScreenSync holds the full configuration for Screen Sync scenes.
     * Present only when Trigger == "screen_sync".
     */
    "screenSync"?: ScreenSyncConfig | null;

    /** Creates a new Scene instance. */
    constructor($$source: Partial<Scene> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("trigger" in $$source)) {
            this["trigger"] = "";
        }
        if (!("devices" in $$source)) {
            this["devices"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scene instance from a string or object.
     */
    static createFrom($$source: any = {}): Scene {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField3_0($$parsedSource["devices"]);
        }
        if ("globalColor" in $$parsedSource) {
            $$parsedSource["globalColor"] = $$createField4_0($$parsedSource["globalColor"]);
        }
        if ("screenSync" in $$parsedSource) {
            $$parsedSource["screenSync"] = $$createField6_0($$parsedSource["screenSync"]);
        }
        return new Scene($$parsedSource as Partial<Scene>);
    }
}

/**
 * SceneCutMode controls whether scene-cut detection is active.
 */
export enum SceneCutMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SceneCutModeOn = "on",
    SceneCutModeOff = "off",
};

/**
 * ScreenSyncConfig is the complete per-scene Screen Sync configuration.
 * All fields have JSON tags so they round-trip through the store unchanged.
 */
export class ScreenSyncConfig {
    /**
     * Capture
     */
    "captureMode": CaptureMode;
    "monitorIndex": number;
    "region": CaptureRect;
    "windowHwnd"?: number;
    "windowTitle"?: string;

    /**
     * Devices assigned to this screen sync scene.
     */
    "deviceIds": string[];

    /**
     * Color extraction
     */
    "colorMode": ColorMode;
    "extractionMethod": ExtractionMethod;
    "multiColorApproach": MultiColorApproach;
    "subMethod": ExtractionMethod;

    /**
     * PaletteStability controls how strongly the scene-palette histogram is
     * accumulated across frames before colours are selected.
     * 0.0 = fully fresh each frame (jittery); 1.0 = stable; 2.0 = ultra-stable.
     * 0.0–1.0 uses histDecay = paletteStability × 0.95.
     * 1.0–2.0 extends hold time up to histDecay=0.99 for extra stability.
     * Only affects MultiColorScenePalette mode.
     * 0.0–2.0
     */
    "paletteStability": number;

    /**
     * Color processing
     * 0.0–2.0; 1.0 = no change
     */
    "saturationBoost": number;

    /**
     * -1.0–+1.0
     */
    "whiteBias": number;

    /**
     * Brightness
     */
    "brightnessMode": BrightnessMode;

    /**
     * 0.1–10.0
     */
    "brightnessMultiplier": number;

    /**
     * Performance preset
     */
    "speedPreset": SpeedPreset;

    /**
     * AssignmentStrategy selects the algorithm that maps extracted colors to devices.
     */
    "assignmentStrategy": AssignmentStrategy;

    /**
     * IdentityLock: fraction of max distance a color must shift before the
     * device anchor is updated. Lower = more stable; higher = adapts faster.
     * 0.10–0.80
     */
    "identityLockBreachThreshold": number;

    /**
     * FlowTrack: EMA blend factor applied to per-device trajectories each frame.
     * Lower = smoother tracking; higher = faster response to content changes.
     * 0.05–1.0
     */
    "flowTrackEmaAlpha": number;

    /**
     * FlowTrackSolveIntervalMs is the minimum time between full Hungarian solves.
     * 16–500
     */
    "flowTrackSolveIntervalMs": number;

    /**
     * SceneCutRemap: ms to hold the post-cut assignment before resuming normal tracking.
     * 0–2000
     */
    "sceneCutRemapHoldMs": number;

    /**
     * ColorSmoothing controls how much hue and saturation changes are damped
     * between frames. 0 = pass-through, 1 = heavy smoothing, 2 = ultra smooth.
     * 0.0–2.0
     */
    "colorSmoothing": number;

    /**
     * AssignmentHandoffMs applies post-assignment per-device color crossfading.
     * Softens visible color-slot swaps by ramping from old to new mapped color.
     * 0–3000
     */
    "assignmentHandoffMs": number;

    /**
     * BrightnessSmoothing controls how much brightness changes are damped.
     * Independent from color so users can suppress brightness flicker while
     * keeping color responsive. 0 = pass-through, 1 = maximum smoothing.
     * 0.0–1.0
     */
    "brightnessSmoothing": number;

    /**
     * BrightnessMaxDeviation is the maximum amount any single light's
     * brightness can deviate from the smoothed frame average. Keeps spatial
     * variation between lights while preventing per-zone jitter from
     * causing visible flicker. 0.01 = very tight, 1.0 = unrestricted.
     * 0.01–1.0
     */
    "brightnessMaxDeviation": number;

    /**
     * SceneCutSensitivity controls how aggressively scene changes are detected.
     * On a detected cut the temporal smoother resets instantly. 0 = rarely
     * detect (only very dramatic changes), 1 = very sensitive.
     * 0.0–1.0
     */
    "sceneCutSensitivity": number;
    "sceneCutMode": SceneCutMode;

    /**
     * BrightnessFloor is the minimum output brightness after smoothing.
     * The full extracted range [0, 1] is linearly remapped into
     * [BrightnessFloor, BrightnessCeiling]. 0 = allow fully dark.
     * 0.0–1.0
     */
    "brightnessFloor": number;

    /**
     * BrightnessCeiling is the maximum output brightness after smoothing.
     * 1.0 = allow full brightness.
     * 0.0–1.0
     */
    "brightnessCeiling": number;

    /** Creates a new ScreenSyncConfig instance. */
    constructor($$source: Partial<ScreenSyncConfig> = {}) {
        if (!("captureMode" in $$source)) {
            this["captureMode"] = CaptureMode.$zero;
        }
        if (!("monitorIndex" in $$source)) {
            this["monitorIndex"] = 0;
        }
        if (!("region" in $$source)) {
            this["region"] = (new CaptureRect());
        }
        if (!("deviceIds" in $$source)) {
            this["deviceIds"] = [];
        }
        if (!("colorMode" in $$source)) {
            this["colorMode"] = ColorMode.$zero;
        }
        if (!("extractionMethod" in $$source)) {
            this["extractionMethod"] = ExtractionMethod.$zero;
        }
        if (!("multiColorApproach" in $$source)) {
            this["multiColorApproach"] = MultiColorApproach.$zero;
        }
        if (!("subMethod" in $$source)) {
            this["subMethod"] = ExtractionMethod.$zero;
        }
        if (!("paletteStability" in $$source)) {
            this["paletteStability"] = 0;
        }
        if (!("saturationBoost" in $$source)) {
            this["saturationBoost"] = 0;
        }
        if (!("whiteBias" in $$source)) {
            this["whiteBias"] = 0;
        }
        if (!("brightnessMode" in $$source)) {
            this["brightnessMode"] = BrightnessMode.$zero;
        }
        if (!("brightnessMultiplier" in $$source)) {
            this["brightnessMultiplier"] = 0;
        }
        if (!("speedPreset" in $$source)) {
            this["speedPreset"] = SpeedPreset.$zero;
        }
        if (!("assignmentStrategy" in $$source)) {
            this["assignmentStrategy"] = AssignmentStrategy.$zero;
        }
        if (!("identityLockBreachThreshold" in $$source)) {
            this["identityLockBreachThreshold"] = 0;
        }
        if (!("flowTrackEmaAlpha" in $$source)) {
            this["flowTrackEmaAlpha"] = 0;
        }
        if (!("flowTrackSolveIntervalMs" in $$source)) {
            this["flowTrackSolveIntervalMs"] = 0;
        }
        if (!("sceneCutRemapHoldMs" in $$source)) {
            this["sceneCutRemapHoldMs"] = 0;
        }
        if (!("colorSmoothing" in $$source)) {
            this["colorSmoothing"] = 0;
        }
        if (!("assignmentHandoffMs" in $$source)) {
            this["assignmentHandoffMs"] = 0;
        }
        if (!("brightnessSmoothing" in $$source)) {
            this["brightnessSmoothing"] = 0;
        }
        if (!("brightnessMaxDeviation" in $$source)) {
            this["brightnessMaxDeviation"] = 0;
        }
        if (!("sceneCutSensitivity" in $$source)) {
            this["sceneCutSensitivity"] = 0;
        }
        if (!("sceneCutMode" in $$source)) {
            this["sceneCutMode"] = SceneCutMode.$zero;
        }
        if (!("brightnessFloor" in $$source)) {
            this["brightnessFloor"] = 0;
        }
        if (!("brightnessCeiling" in $$source)) {
            this["brightnessCeiling"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenSyncConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ScreenSyncConfig {
        const $$createField2_0 = $$createType6;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("region" in $$parsedSource) {
            $$parsedSource["region"] = $$createField2_0($$parsedSource["region"]);
        }
        if ("deviceIds" in $$parsedSource) {
            $$parsedSource["deviceIds"] = $$createField5_0($$parsedSource["deviceIds"]);
        }
        return new ScreenSyncConfig($$parsedSource as Partial<ScreenSyncConfig>);
    }
}

export class Settings {
    "pollIntervalMs": number;
    "startMinimized": boolean;
    "launchAtLogin": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("pollIntervalMs" in $$source)) {
            this["pollIntervalMs"] = 0;
        }
        if (!("startMinimized" in $$source)) {
            this["startMinimized"] = false;
        }
        if (!("launchAtLogin" in $$source)) {
            this["launchAtLogin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * SpeedPreset bundles FPS target, update interval, and transition duration.
 */
export enum SpeedPreset {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SpeedPresetVerySlow = "very_slow",
    SpeedPresetSlow = "slow",
    SpeedPresetMedium = "medium",
    SpeedPresetFast = "fast",
    SpeedPresetRealtime = "realtime",
};

// Private type creation functions
const $$createType0 = lights$0.DeviceState.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = lights$0.Color.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = ScreenSyncConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = CaptureRect.createFrom;
const $$createType7 = $Create.Array($Create.Any);
