// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export enum Brand {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BrandLIFX = "lifx",
    BrandHue = "hue",
    BrandElgato = "elgato",
    BrandGovee = "govee",
};

export class Color {
    "h": number;
    "s": number;
    "b": number;

    /** Creates a new Color instance. */
    constructor($$source: Partial<Color> = {}) {
        if (!("h" in $$source)) {
            this["h"] = 0;
        }
        if (!("s" in $$source)) {
            this["s"] = 0;
        }
        if (!("b" in $$source)) {
            this["b"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Color instance from a string or object.
     */
    static createFrom($$source: any = {}): Color {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Color($$parsedSource as Partial<Color>);
    }
}

export class Device {
    "id": string;
    "brand": Brand;
    "name": string;
    "model"?: string;
    "lastIp": string;
    "lastSeen": time$0.Time;
    "supportsColor": boolean;
    "supportsKelvin": boolean;

    /**
     * MinKelvin/MaxKelvin are the device's supported colour-temperature range in Kelvin.
     * Zero means the field is not known (use the UI default).
     */
    "minKelvin"?: number;
    "maxKelvin"?: number;
    "kelvinStep"?: number;

    /**
     * FirmwareVersion is the device's reported software/firmware version string.
     */
    "firmwareVersion"?: string;

    /**
     * Room is the user-assigned room label for grouping (e.g. "Bedroom", "Office").
     */
    "room"?: string;

    /** Creates a new Device instance. */
    constructor($$source: Partial<Device> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("brand" in $$source)) {
            this["brand"] = Brand.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("lastIp" in $$source)) {
            this["lastIp"] = "";
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = null;
        }
        if (!("supportsColor" in $$source)) {
            this["supportsColor"] = false;
        }
        if (!("supportsKelvin" in $$source)) {
            this["supportsKelvin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     */
    static createFrom($$source: any = {}): Device {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Device($$parsedSource as Partial<Device>);
    }
}

export class DeviceState {
    "on": boolean;
    "brightness": number;
    "color"?: Color | null;
    "kelvin"?: number | null;

    /** Creates a new DeviceState instance. */
    constructor($$source: Partial<DeviceState> = {}) {
        if (!("on" in $$source)) {
            this["on"] = false;
        }
        if (!("brightness" in $$source)) {
            this["brightness"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceState instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceState {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("color" in $$parsedSource) {
            $$parsedSource["color"] = $$createField2_0($$parsedSource["color"]);
        }
        return new DeviceState($$parsedSource as Partial<DeviceState>);
    }
}

// Private type creation functions
const $$createType0 = Color.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
