// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MonitorInfo describes a display known to the OS.
 */
export class MonitorInfo {
    "index": number;
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "isPrimary": boolean;
    "name": string;

    /** Creates a new MonitorInfo instance. */
    constructor($$source: Partial<MonitorInfo> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorInfo($$parsedSource as Partial<MonitorInfo>);
    }
}

/**
 * WindowInfo describes a visible application window.
 */
export class WindowInfo {
    "hwnd": number;
    "title": string;
    "exeName": string;

    /** Creates a new WindowInfo instance. */
    constructor($$source: Partial<WindowInfo> = {}) {
        if (!("hwnd" in $$source)) {
            this["hwnd"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("exeName" in $$source)) {
            this["exeName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowInfo($$parsedSource as Partial<WindowInfo>);
    }
}
