// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateScene(arg1) {
  return window['go']['main']['App']['ActivateScene'](arg1);
}

export function AddHueBridge(arg1, arg2) {
  return window['go']['main']['App']['AddHueBridge'](arg1, arg2);
}

export function CheckCameraNow() {
  return window['go']['main']['App']['CheckCameraNow']();
}

export function CreateScene(arg1) {
  return window['go']['main']['App']['CreateScene'](arg1);
}

export function DeleteScene(arg1) {
  return window['go']['main']['App']['DeleteScene'](arg1);
}

export function DiscoverHueBridges() {
  return window['go']['main']['App']['DiscoverHueBridges']();
}

export function DiscoverLights() {
  return window['go']['main']['App']['DiscoverLights']();
}

export function GetActiveScene() {
  return window['go']['main']['App']['GetActiveScene']();
}

export function GetCameraState() {
  return window['go']['main']['App']['GetCameraState']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetHueBridges() {
  return window['go']['main']['App']['GetHueBridges']();
}

export function GetLightState(arg1) {
  return window['go']['main']['App']['GetLightState'](arg1);
}

export function GetScene(arg1) {
  return window['go']['main']['App']['GetScene'](arg1);
}

export function GetScenes() {
  return window['go']['main']['App']['GetScenes']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsMonitoringEnabled() {
  return window['go']['main']['App']['IsMonitoringEnabled']();
}

export function PairHueBridge(arg1) {
  return window['go']['main']['App']['PairHueBridge'](arg1);
}

export function SetLightState(arg1, arg2) {
  return window['go']['main']['App']['SetLightState'](arg1, arg2);
}

export function SetMonitoringEnabled(arg1) {
  return window['go']['main']['App']['SetMonitoringEnabled'](arg1);
}

export function TurnOffLight(arg1) {
  return window['go']['main']['App']['TurnOffLight'](arg1);
}

export function TurnOnLight(arg1) {
  return window['go']['main']['App']['TurnOnLight'](arg1);
}

export function UpdateScene(arg1) {
  return window['go']['main']['App']['UpdateScene'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
