// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {store} from '../models';
import {discovery} from '../models';
import {lights} from '../models';

export function ActivateScene(arg1:string):Promise<void>;

export function AddHueBridge(arg1:string,arg2:string):Promise<void>;

export function CheckCameraNow():Promise<boolean>;

export function CreateScene(arg1:main.CreateSceneRequest):Promise<store.Scene>;

export function DeleteScene(arg1:string):Promise<void>;

export function DiscoverHueBridges():Promise<Array<discovery.DiscoveredHueBridge>>;

export function DiscoverLights():Promise<main.DiscoverResult>;

export function GetActiveScene():Promise<string>;

export function GetCameraState():Promise<boolean>;

export function GetDevices():Promise<Array<lights.Device>>;

export function GetHueBridges():Promise<Array<store.HueBridge>>;

export function GetLightState(arg1:string):Promise<lights.DeviceState>;

export function GetScene(arg1:string):Promise<store.Scene>;

export function GetScenes():Promise<Array<store.Scene>>;

export function GetSettings():Promise<store.Settings>;

export function IsMonitoringEnabled():Promise<boolean>;

export function PairHueBridge(arg1:string):Promise<main.PairResult>;

export function SetLightState(arg1:string,arg2:lights.DeviceState):Promise<void>;

export function SetMonitoringEnabled(arg1:boolean):Promise<void>;

export function TurnOffLight(arg1:string):Promise<void>;

export function TurnOnLight(arg1:string):Promise<void>;

export function UpdateScene(arg1:store.Scene):Promise<void>;

export function UpdateSettings(arg1:store.Settings):Promise<void>;
