// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';
import {discovery} from '../models';
import {lights} from '../models';
import {capture} from '../models';

export function ActivateScene(arg1:string):Promise<void>;

export function AddHueBridge(arg1:string,arg2:string):Promise<void>;

export function CheckCameraNow():Promise<boolean>;

export function CloneScene(arg1:string):Promise<store.Scene>;

export function CreateScene(arg1:main.CreateSceneRequest):Promise<store.Scene>;

export function DeactivateScene():Promise<void>;

export function DeleteScene(arg1:string):Promise<void>;

export function DiscoverHueBridges():Promise<Array<discovery.DiscoveredHueBridge>>;

export function DiscoverLights():Promise<main.DiscoverResult>;

export function GetActiveScene():Promise<string>;

export function GetCameraState():Promise<boolean>;

export function GetCapturePreview():Promise<string>;

export function GetDefaultScreenSyncConfig():Promise<store.ScreenSyncConfig>;

export function GetDevices():Promise<Array<lights.Device>>;

export function GetHueBridges():Promise<Array<store.HueBridge>>;

export function GetLastSceneID():Promise<string>;

export function GetLightState(arg1:string):Promise<lights.DeviceState>;

export function GetMonitors():Promise<Array<capture.MonitorInfo>>;

export function GetScene(arg1:string):Promise<store.Scene>;

export function GetScenes():Promise<Array<store.Scene>>;

export function GetScreenSyncState():Promise<main.ScreenSyncState>;

export function GetSettings():Promise<store.Settings>;

export function GetWindowThumbnail(arg1:number):Promise<string>;

export function GetWindows():Promise<Array<capture.WindowInfo>>;

export function IsMonitoringEnabled():Promise<boolean>;

export function PairHueBridge(arg1:string):Promise<main.PairResult>;

export function QuitApp():Promise<void>;

export function RemoveDevice(arg1:string):Promise<void>;

export function RemoveHueBridge(arg1:string):Promise<void>;

export function SetDeviceRoom(arg1:string,arg2:string):Promise<void>;

export function SetLightState(arg1:string,arg2:lights.DeviceState):Promise<void>;

export function SetMonitoringEnabled(arg1:boolean):Promise<void>;

export function StartRegionSelect():Promise<void>;

export function StopScreenSync():Promise<void>;

export function TurnOffLight(arg1:string):Promise<void>;

export function TurnOnLight(arg1:string):Promise<void>;

export function UpdateScene(arg1:store.Scene):Promise<void>;

export function UpdateScreenSyncConfig(arg1:string,arg2:store.ScreenSyncConfig):Promise<void>;

export function UpdateSettings(arg1:store.Settings):Promise<void>;
